#!/usr/bin/env python3
"""Render a FinPerturb-owned FinMem config, with the model taken from the environment.

FinMem reads its model from a TOML file, not from the environment, so something
has to carry BACKBONE_MODEL across. That something is this script rather than an
edit to agents/finmem: the repo stays byte-for-byte at be814aa, which is what
keeps the experiment's claim about the published agent instead of about our
version of it. Pass the output to run.py with -cp.

WHY [chat] IS ASSERTED TO HOLD EXACTLY THREE KEYS. LLMAgent.__init__ deletes
end_point, model and system_message from the chat config and hands EVERYTHING
ELSE to ChatOpenAICompatible as other_parameters, which are merged straight into
the request body (chat.py:127). So a stray `temperature = 0` in this file would
silently become a sampling parameter on every call -- and §8.3 exists precisely
because a pinned temperature hides the instability being measured rather than
removing it. The default-decoding guarantee is not a policy here; it is the
absence of keys in this table, and absence is easy to break by accident.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import toml

# The three keys LLMAgent consumes by name. Anything else in [chat] reaches the
# provider as a request parameter.
CHAT_KEYS = {"model", "end_point", "system_message"}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--base",
        type=Path,
        default=Path("agents/finmem/config/tsla_gpt_config.toml"),
        help="upstream config to derive from; read only, never written",
    )
    parser.add_argument("--out", type=Path, default=Path("data/generated/finmem_config.toml"))
    parser.add_argument("--model", default=os.environ.get("BACKBONE_MODEL", ""))
    args = parser.parse_args(argv)

    if not args.model:
        print("BACKBONE_MODEL is unset and --model was not given", file=sys.stderr)
        return 1
    if not args.base.exists():
        print(f"base config not found: {args.base}", file=sys.stderr)
        return 1

    config = toml.load(args.base)
    previous = config["chat"].get("model")
    config["chat"]["model"] = args.model

    extra = set(config["chat"]) - CHAT_KEYS
    if extra:
        print(
            f"[chat] carries unexpected keys {sorted(extra)}; these would be sent as request "
            "parameters on every call. Remove them or add them to CHAT_KEYS deliberately.",
            file=sys.stderr,
        )
        return 1

    # FinMem picks its response parser with model.startswith("gpt") and raises
    # NotImplementedError otherwise -- from inside the call, after it is paid for.
    if not args.model.startswith(("gpt", "gemini-pro", "tgi")):
        print(f"model {args.model!r} will fail FinMem's parse_response dispatch", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as handle:
        handle.write("# GENERATED by harness/render_config.py -- do not edit.\n")
        handle.write(f"# derived from {args.base}\n")
        handle.write("# model comes from BACKBONE_MODEL; everything else is upstream's.\n\n")
        toml.dump(config, handle)

    print(f"wrote {args.out}")
    print(f"  model:    {previous} -> {args.model}")
    print(f"  endpoint: {config['chat']['end_point']}")
    print(f"  symbol:   {config['general']['trading_symbol']}")
    print(f"  [chat] keys: {sorted(config['chat'])}  (no sampling parameters -> default decoding)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
